### ISSUE TITLE
spec license missing

### ISSUE THREAD

**Issue by Jan200101** [UnitedRPMs/v4l2loopback#1]
the spec file this is based upon has been taken from here
https://pagure.io/v4l2loopback-fedora
which is a fork from
https://github.com/danielkza/v4l2loopback-fedora
following that this repo must contain a copy of the license

**Comment by kuboosoft** [comment]
@Jan200101 Thanks for the report, please read the [Disclaimer](https://github.com/UnitedRPMs/WIKI/wiki/Disclaimer).
